aolabNeuro/analyze

- aopy/preproc.py
> updated doc strings for trial_align functions

- aopy/analysis.py
- setup.py
- tests/test_analysis.py
Add functions to find the trough and peak time of a spike waveform
> Ryan add to analysis.py

- aopy/preproc.py
- tests/test_preproc.py
not sure if check_alternating should be on by default. also whether that's a good name for it
> modify detect_edges

- aopy/analysis.py
- aopy/precondition.py
- aopy/utils.py
- aopy/visualization.py
- tests/test_precondition.py
Updated docstrings, generalized buttterworth filter function and modified the same function to run without a loop for multiple channels.
> Pavi preproc

- docs/source/utils.rst
This adds a utils.rst file for the Utils.py module
> Add: Utils documentation page (utils.rst)

- aopy/utils.py
- tests/test_utils.py
Fo lab meeting - documentation review
> Pavi fn pca

- aopy/analysis.py
- tests/test_analysis.py
function to quantify PCA dimensions required to account for a specified variance.
> check_pca_dims function & test

- aopy/data.py
- aopy/torch.py
- docs/source/index.rst
- docs/source/torch.rst
- setup.py
- tests/test_data.py
- tests/test_torch.py
is this ok? moving the torch stuff to a different file means it doesn't have to be required for install, i think. since pytorch is quite a large package (~1GB for me)
> move torch to separate folder, not required

- aopy/data.py
- tests/test_data.py
I've added data compression support to `data.save_hdf()`. Please review.
> Compress hdf5

- aopy/precondition.py
- tests/test_precondition.py
Quick update, the bin spikes function should take the sum of the spike counts rather than the mean.
> update bin spikes

- aopy/data.py
- tests/test_data.py
Not sure if this is what you had in mind.
> Add data.map_elec2acq

- aopy/preproc.py
- tests/test_preproc.py
1. Any suggestions on the function name?
2. I'm not quite sure how this needs to be added to prepare_bmi3d.
Issue #161
> Timestamps to timeseries interpolation function

- docs/aolab_analyze_samplenotebook.ipynb
- docs/source/examples.rst
- docs/source/examples/20211004_aolabs_analyze_samplenotebook.ipynb
Google colab or python notebook with a sample aopy function and some notes from getting started
See https://github.com/aolabNeuro/analyze/issues/141 for more notes
> [ISSUE #141] Google colab/python notebook with examples

- aopy/visualization.py
- tests/test_visualization.py
plot_circles function acts as plot_targets but adds color selection as a parameter - test is currently unstable (possibly just animate issues) and z-axis needs correction
> Gus issue 114

- aopy/precondition.py
- tests/test_precondition.py
[#178](https://github.com/aolabNeuro/analyze/issues/178)
> data is transposed at the beginning of the functioon

- aopy/postproc.py
- aopy/precondition.py
- tests/test_postproc.py
- tests/test_precondition.py
In progress, still need to add other functions and tests
> Get instantaneous target direction.

- aopy/analysis.py
- tests/test_analysis.py
forgot to change a variable when cleaning up code
> fix classify cell types wrapper

- aopy/preproc/base.py
- tests/test_preproc.py
> fix interp timestamps monotonicity bug

- aopy/precondition.py
- tests/test_precondition.py
[215](https://github.com/aolabNeuro/analyze/issues/215) I made code to bin spike times. I'd completely forgotten that spike times' shape could vary at each trial and electrode. I also didn't know how spike times are stored in experiments, so I focused on 1D spike times.
> code to bin spike times

- aopy/analysis.py
- tests/test_analysis.py
hi, adding an option to the calc_max_erp() function to return a max erp for every trial
> add trial average option

- aopy/analysis.py
- aopy/preproc/bmi3d.py
- tests/test_preproc.py
i set the search radius to 1/fps
and i added some debug options to make it easier to quickly see if things are aligned.
> add debug options to laser stim times

- aopy/preproc/bmi3d.py
Adjusted slightly the algorithm to check both onset and offset times independently first, then combine them later in case there are different number of ons and offs
> correct both onset and offset times

- aopy/preproc/bmi3d.py
minor change to the way search radius is computed by default
> change search radius

- aopy/analysis/behavior.py
- tests/test_analysis.py
couldn't fix the other pull request so i made a new one
> Leo trials metrics 2

- .github/workflows/main.yml
- aopy/utils/base.py
fixes #349; can you check that test_utils.py works now?
> import inside functions

- aopy/precondition/base.py
- tests/test_data.py
- tests/test_precondition.py
closes #360 by upsampling first to the lowest common multiple sampling rate
> Leo fix downsample

- aopy/data/bmi3d.py
#365 Changed AnalogPanel to DigitalPanel in load_ecube_digital
> Changed AnalogPanel to DigiralPanel

- aopy/postproc/base.py
address #375 and improve performance by vectorizing the matrix multiplication
> speed up rotate data and nudge in all axes

- aopy/analysis/base.py
- aopy/analysis/behavior.py
- tests/test_analysis.py
Adding a function to do rolling averages where the output is the full size of the input but the invalid indices are replaced with the first and last valid values.
> Leo add rolling average

- aopy/data/bmi3d.py
- aopy/postproc/base.py
- tests/test_data.py
> Rounded numbers

- aopy/visualization/__init__.py
- aopy/visualization/animation.py
- aopy/visualization/base.py
- docs/source/visualization.rst
- tests/test_visualization.py
- refactored animation functions into visualization.animation
- added animate_cursor_eye() function
- removed 1e6 scaling from plot_timeseries() and plot_freq_domain_amplitude()
- added kwargs to plot_trajectories
- changed plot_boxplots to allow non-rectangular data
closes #221 
closes #382 
closes #203
> Leo eyetracking poster functions

- aopy/postproc/base.py
> Fixed import

- aopy/__init__.py
- aopy/utils/__init__.py
- aopy/utils/base.py
- aopy/utils/memory.py
- docs/source/examples/memory_limit_example.ipynb
- docs/source/quickstart.rst
- docs/source/utils.rst
old PR was broken for some reason and didn't include my new changes
> Leo memory default

- aopy/analysis/behavior.py
- aopy/postproc/base.py
- tests/test_analysis.py
- tests/test_postproc.py
@pavi-rajes wrote this code, I've edited it and added test functions. I had to also modify postproc.rotate_spatial_data() to get this working.
> Add movement error

- aopy/analysis/base.py
Added dtype option in the function so that we can change dtype for memory issues.
> Added dtype option in calc_mt_tfr

- LICENSE
- MANIFEST.in
- README.md
- aopy/data/base.py
- aopy/data/bmi3d.py
- docs/source/conf.py
- docs/source/contributing.rst
- docs/source/quickstart.rst
- setup.py
made some changes to the config files to allow us to upload to pypi. 
- needed to change the way config files were located so we don't always need to use editing mode (pip install -e) 
- added MIT license
- bumped version to 0.6.2
to upload to pypi I also added an SOP to the drive in "Lab documents/Regulatory\/Safety/2. Process SOPs/PyPI SOP"
> add aopy to pypi

- aopy/preproc/neuropixel.py
Added argument to modify inter_barcode_interval
> change inter_barcode_interval

- aopy/precondition/base.py
- tests/test_precondition.py
Get waveforms and unit positions from raw data in neuropixels, using spike indices of each unit obtained by kilosort
> Calc waveforms from kilosort output data

- aopy/utils/base.py
Barcode algorithm sometimes didn't work when all barcodes are not unique. This improvement doesn't solve the fundamental problem. But for the specific dataset, it helps synchronize both streams.
> Modified get_first_last_times

- docs/source/data.rst
I forgot to add the db module into the docs
> add db docs

- aopy/preproc/neuropixel.py
- tests/test_preproc.py
Modified code a little bit. When a bad trial list is given, this code removes the trials and concatenate data by chunk because I ran into a memory issue. Also this returns the saved directory names where concatenated data is. Also
> Changed code so that it remove bad trials in concatenating data across sessions

- aopy/data/eye.py
minor fix to proc_eye_day. for some reason the flash experiments sometimes yield a 1.0 correlation, even though there's no cursor data? not sure.
i still want to make a version of this function that doesn't modify the preprocessed files, but this works for now.
> change criteria

- .readthedocs.yaml
- aopy/analysis/base.py
- aopy/preproc/base.py
- tests/test_analysis.py
- tests/test_preproc.py
- changed axis from (ntr, nt, nch) to (nt, nch, ntr)
- separated find_max_erp() from calc_max_erp()
> swap erp axis

- aopy/analysis/base.py
i updated the example with the new test and added some notes about scipy coherence
> add more coherence notes

- aopy/preproc/bmi3d.py
- tests/test_preproc.py
forgot to update erp axes in the tests for other functions
> fix erp tests

- aopy/analysis/base.py
- aopy/data/base.py
- aopy/data/bmi3d.py
- tests/test_analysis.py
- tests/test_data.py
some minor fixes to dimensions of things. added a couple tests that were failing but now they work.
> tfcoh and tabulate_kinematics fixes

- aopy/data/bmi3d.py
- tests/test_data.py
> add helper fn for task codes

- aopy/data/bmi3d.py
to be able to load the mask across experiments using tabulate_kinematic_data
> add eye closed mask to get_kinematics

- aopy/postproc/base.py
- tests/test_postproc.py
Functions to get trial mask to extract the same number of trials for each target after removing trials
> Get conditioned trials per target

- aopy/analysis/behavior.py
- tests/test_analysis.py
Functions to get movement onset and times when the cursor leaves the center target
> Movement onset

- setup.py
specify bmi3d version so that we can make updates for rig2 without breaking aopy
> clarify bmi3d version

- aopy/data/base.py
- aopy/data/bmi3d.py
fixing my assumption that hdf data is static
> add default false to caching functions

- aopy/data/db.py
quick fix to make it easier to use other databases
> add dbname option

- aopy/analysis/behavior.py
- tests/test_analysis.py
- Low pass filter speed to remove noise
- Threshold option to use the same threshold across trials, without computing threshold at each trial
> Added low pass filtering and threshold

- setup.py
- tests/test_data.py
> add explicit dbname

- aopy/data/optitrack.py
the version of exported csv data has changed from 1.23 to 1.24
> increase version compatibility

- aopy/tutorial_functions.py
- tests/test_tutorial_functions.py
Add function practice_function_matt to tutorial_functions.py
> Matt's github practice

- aopy/data/db.py
instead of having to do `entry.record.sequence.generator.name` you can do `entry.sequence_name`
> add sequence name to db

- aopy/data/bmi3d.py
there was a missing shape transformation for feature extractors with multiple frequency bands
> add reshape extract_lfp_features

- aopy/data/db.py
- aopy/preproc/wrappers.py
- tests/test_data.py
added a preproc function to db
> db preproc

- aopy/visualization/animation.py
ability to specify the clim for an animation
> add clim to spatial map

- aopy/data/db.py
> fix db bug

- aopy/data/db.py
- tests/test_data.py
> fix broken filters

- aopy/visualization/base.py
> add theta to place_subplots

- aopy/preproc/neuropixel.py
- tests/test_preproc.py
synchronize time series data by padding or cropping
> synchronize time series data

- aopy/preproc/neuropixel.py
Removed redundant parts in synchronization of ecube and neuropixels
> Fixed synchronization bugs

- aopy/preproc/neuropixel.py
- docs/source/conf.py
- setup.py
- tests/test_preproc.py
Devide data into batches and destripe lfp data at each batch.
> destripe lfp batch

- aopy/utils/base.py
- tests/test_utils.py
Multiply a matrix by long data in each batch to save memory.
> Multiply matrix by huge data

- aopy/data/bmi3d.py
Update tabulate center out to include all possible penalty codes.
> add delay penalty to list of penalty codes

- aopy/analysis/behavior.py
- tests/test_analysis.py
Update function to account for cursor radius when computing cursor leave time
> Update cursor leave time func

- aopy/data/bmi3d.py
The columns were updated but the descriptions were not
> Fix docstring

- aopy/postproc/neuropixel.py
Was loading all clusters over and over again even if they repeated so it was taking forever. We only need to load each cluster once.
> fix function to load template amplitudes saved by kilosort

- aopy/data/bmi3d.py
forgot to apply change to one function
> fix key for emg

- aopy/analysis/base.py
- tests/test_analysis.py
some wrappers to calculate statistics on tfr data
> band statistics

- aopy/analysis/base.py
- tests/test_analysis.py
combining the functionality of calc_spatial_map_correlation and calc_tfr_mean
> add tf-correlation functions

- aopy/preproc/quality.py
> fix detect_bad_ch_outliers image

- aopy/data/bmi3d.py
- aopy/visualization/base.py
add try/except to tabulate_stim_data
fix laser sensor idx
fix plotting multiple maps function if only one map is present
> fix stim bugs

- aopy/analysis/connectivity.py
- aopy/analysis/latency.py
remove so i don't get a spam of output in the console when running bootstraps
> remove tqdm
