aopy/data.py, aopy/preproc.py, docs/source/preproc.rst, docs/source/quickstart.rst, tests/test_preproc.py
Fixed the versioning to allow newer versions to be preprocessed with old code
Change the structure of `clock` and `events` to include different versions of timing:
- bmi3d's internal timing 
- sync timing from bmi3d to ecube
- measured timing of the screen
Added documentation for the preprocessed data structures
=> Preproc fixes

aopy/data.py, tests/test_data.py
i added a function to load an ecube file one chunk at a time, where the chunk size is a number of samples. i will use this function in bmi3d to simulate data being streamed by the ecube, which arrives in 728-sample packets. 
let me know what you think.
=> Load ecube chunks

aopy/preproc.py, tests/test_preproc.py
If 'trigger_times' was longer than the input data/samplerate the function broke. Fixed it by only using triggers that are contained within the data.
=> fix_trial_align_data

aopy/data.py
1) adding a note in pkl_wwrite() that hdf files can not be pickled using this function
2) Added reference to save_hdf function along with the note 
3) data_dict input in save_hdf() is not optional input. Updated misleading docstrings.
=> updating docstrings

aopy/analysis.py, tests/test_analysis.py
Ended up deciding allow the function to accommodate rolling success metric calculations and 'global' calculations through the optional argument 'window_size'. I updated the existing 'calc_success_rate' function become 'calc_success_percent' and wrote a new 'calc_success_rate' function that outputs results in units of [success/s].
=> add rolling success metrics

aopy/preproc.py, tests/test_preproc.py
proc_eyetracking can now return eye data, add optional bool to control saving the data to filesystem. 
This will allow for quickly recalculating eye tracking data without touching filesystem. 
Testing: ran updated unit test
=> Make proc_eyetracking return eye data

aopy/preproc/bmi3d.py
i haven't really tested whether this makes a difference, but this is a very glaring bug in the preproc code for timestamps, i think it affects about half of experiments, at random. might explain some things?
=> missing line

aopy/analysis.py, aopy/preproc/base.py, tests/test_analysis.py, tests/test_preproc.py
I added two functions:  time_to_target() and path_length() in analysis.py 
time_to_target() calculates reach time provided event codes and event times with an option to get per target statistics. Path length calculates the total distance traveled from cursor x and cursor y positions changing across time.  
In the same pull request, also adding another function get_trail_segments_and_times() in preproc.base. This function returns all corresponding event times along with event codes. 
Notes: 
Currently, time_to_target() only estimates reach times on successful targets. In the future, we can make it optional by adding an optional lamba reward filter function in the input. But I will treat this as an enhancement and this pull request need not wait for it.
=> Behavior metrics

aopy/data/bmi3d.py, tests/test_data.py
using `get_target_locations()` is tricky because if you try to get target 10 and there are only 9 targets, it gives you a cryptic error about index 0 being out of bounds. I added a more descriptive error message to help with debugging.
=> Leo update get target locations

README.md, aopy/preproc/bmi3d.py, docs/source/test-guidelines.rst, tests/test_preproc.py, tests/test_utils.py
There was a bug for experiments that don't have sync events that prevented preprocessing. I added a check of the length of sync events to avoid this problem.
=> Fix no event bug

aopy/data/db.py, tests/test_data.py
keeping date as a datetime object makes comparisons easier later
=> remove str() from db.list_entry_details

aopy/preproc/wrappers.py, tests/test_preproc.py
minor fix to always save the eye closed mask. it was getting thrown away for data without calibration
=> always include eye closed mask

aopy/data/bmi3d.py, aopy/whitematter/dataset.py
don't know if it works, but might be able to load corrupted ecube files by truncating the end where the corruption happened
=> maybe load corrupted files

aopy/data/bmi3d.py, aopy/precondition/base.py, aopy/precondition/eye.py, aopy/preproc/bmi3d.py, aopy/preproc/oculomatic.py, tests/test_precondition.py
we can use preproc=aopy.precondition.filter_kinematics() instead if needed
=> remove default filtering in get_interp_kinematics

aopy/postproc/base.py, tests/test_postproc.py
This function chooses trials so that the number of trials per target can be the same across targets. But the order of target index was completely random. This sometimes caused problems when I did decoding analysis. I changed the code so that target index could be aligned like [1,2,3,4,5,6,7,8,1,2,3,4,5,...], not completely random order.
=> Changed so that target index could be aligned in the ascending order

aopy/analysis/base.py, tests/test_analysis.py
Computes a confidence interval from cdf in data samples, not a confidence interval in the mean of samples.
Computes a overlap ratio (0 to 1) between 2 confidence intervals
=> Get a confidence interval and compute overlap ratio between 2 confidence intervals

aopy/data/base.py
increase cache size from 1 to 2 because in load_exp_data and other functions the load_hdf_group function gets called twice
=> speedup load_exp_data

aopy/data/db.py, setup.py, tests/test_data.py
maybe useful utility to add one or more columns to a dataframe with metadata from task entries from the database. i envision it being used after you create a df using tabulate_behavior_data functions but want extra info about the experiment rotations, e.g.
=> add metadata columns function

aopy/data/base.py
sometimes the preproc errors are getting saved as bytes instead of strings, which was causing problems when printing them out
=> fix preproc error loading

aopy/analysis/base.py
I think the readthedocs autodoc importer doesn't like -np.inf for some reason. The long shows this:
`WARNING: autodoc: failed to import module 'analysis.base' from module 'aopy'; the following exception was raised:
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/analyze/envs/latest/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 58, in import_module
return importlib.import_module(modname)
File "/home/docs/.asdf/installs/python/3.9.20/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line …
=> change func optional args to remove -np.inf

aopy/preproc/bmi3d.py
fix an issue with some flash experiments that technically have kinematics but they are full of nan values
=> don't interp without non-nan data

aopy/analysis/latency.py, tests/test_analysis.py
avoid some wasted time repeatedly spinning up parallel processes by letting the user manage a parallel pool themselves
=> allow parallel pool as input

aopy/data/bmi3d.py
This ensures that reward & penalty columns are always bool, even after concatenating an empty df (which turns the reward and penalty column values in the existing df to float)
=> katherine-update-tabulate-behavior
